// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
)

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	CreatedAt string `json:"created_at"`
}

type UsersWeight struct {
	UserID   string `json:"user_id"`
	WeightID string `json:"weight_id"`
}

type Weight struct {
	ID         string         `json:"id"`
	Date       string         `json:"date"`
	Weight     float64        `json:"weight"`
	WeightUnit string         `json:"weight_unit"`
	Note       sql.NullString `json:"note"`
}
